# ~/.tmux.conf

# remap prefix from 'C-b' to 'C-p'
unbind C-b
set-option -g prefix C-p
bind-key C-p send-prefix

# split panes using \ and -
bind '\' split-window -h
bind - split-window -v
unbind '"'
unbind %

# easy reload
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D

set -g mouse on
set-option -g allow-rename off
set -g default-terminal 'tmux-256color'
set -g terminal-features 'xterm*:clipboard:ccolour:cstyle:focus:title,screen*:title,rxvt*:ignorefkeys,xterm-ghostty:RGB,ghostty:RGB'
set -g xterm-keys on

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows sequentially if you close one
set -g renumber-windows on

### VSCode - tmux integration ###
set -ga update-environment 'PATH VSCODE_IPC_HOOK_CLI TERM_PROGRAM'
### VSCode - tmux integration ###

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'mahoon2/p10k-tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g @p10k_tmux_modules_right "application cpu ram battery uptime"
set -g @p10k_tmux_window_text "#{window_name}"
set -g @p10k_tmux_window_attention_pattern 'Action [Rr]equired'
set -g @p10k_tmux_window_idle_pattern '^✳'
set -g @p10k_tmux_window_working_pattern '^[⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏]'
set -g @p10k_tmux_window_name_max_length "24"
set -g @p10k_tmux_module_left_pad " "
set -g @p10k_tmux_module_right_pad " "
set -g @p10k_tmux_module_gap " "
set -g @p10k_tmux_module_battery_icon "󰁹"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
